// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
)

// Pong defines model for Pong.
type Pong struct {
	Ping string `json:"ping"`
}

func HandleRequest(ctx context.Context, request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	switch request.Path {
	// /ping
	case "/ping":
		return GetPing(ctx, request)
	default:
		return events.APIGatewayProxyResponse{StatusCode: http.StatusNotFound}, fmt.Errorf("unknown path")
	}
}

// (GET /ping)
func GetPing(ctx context.Context, request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	if request == nil {
		return nil, fmt.Errorf("received nil event")
	}
	return events.APIGatewayProxyResponse{}, nil

}

func main() {
	lambda.Start(HandleRequest)
}
